# Generated by Django 3.2.9 on 2022-03-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_auto_20220315_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
